In [1]:
import json

In [2]:
with open('train.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [10]:
data['data'][0]

{'id': 0,
 'noisy_add': 'đông lân 1 , phường bà điểm , hồ chí minh',
 'std_add': {'1580': {'street': 'đông lân 1',
   'city': 'hồ chí minh',
   'id': 1580,
   'district': 'hóc môn',
   'ward': 'None'}}}

In [15]:
def gen_data(data_file, num_sample):
    with open(data_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    x = dict()
    x['data'] = []
    for i in range(num_sample):
        x['data'].append(data['data'][i])
    return x

In [16]:
train_data = gen_data('train.json', 1000)
with open('Siameser/Data/train.json', 'w', encoding='utf-8') as f:
    json.dump(train_data, f, ensure_ascii=False, indent=4)

In [17]:
test_data = gen_data('test.json', 500)
with open('Siameser/Data/test.json', 'w', encoding='utf-8') as f:
    json.dump(test_data, f, ensure_ascii=False, indent=4)

In [18]:
with open('Siameser/Data/RAT_DATA_MAIN.json', 'r', encoding='utf-8') as f:
    RAT_DATA = json.load(f)

In [ ]:
RAT_DATA

In [21]:
std_addresses = []
for sample in RAT_DATA['data']:
    std_addresses.append(sample['norm_add'])

In [25]:
# from collections import Counter
# for i in Counter(std_addresses):
#     print(i)
#     break

In [26]:
x = dict(Counter(std_addresses))
hard_add = []
for i in x:
    if x[i] > 1:
        hard_add.append(i)

In [28]:
len(hard_add)

515

In [31]:
hard_id = []
for sample in RAT_DATA['data']:
    if sample['norm_add'] in hard_add:
        hard_id.append(sample['id'])

In [34]:
# hard_id

In [42]:
with open('train.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
hard_sample = []
for sample in data['data']:
    id = (list(sample['std_add'].keys())[0])
    if sample['std_add'][id]['id'] in hard_id:
        hard_sample.append(sample)  

In [1]:
hard_sample

NameError: name 'hard_sample' is not defined

In [45]:
with open('Siameser/Data/hard_train.json', 'w', encoding='utf-8') as f:
    json.dump(test_data, f, ensure_ascii=False, indent=4)

In [1]:
import json

In [2]:
with open ('Data/train.json', 'r', encoding='utf-8') as f:
    train_data = json.load(f)

In [ ]:
train_data

# Add more standard address

In [30]:
import json
with open ('Data/RAT_DATA_MAIN_New.json', 'r', encoding='utf-8') as f:
    RAT_DATA = json.load(f)

In [4]:
# x = dict()
# for i in RAT_DATA['data']:
#     # print(i)
#     id = i['id']
#     x[id] = dict()
#     x[id]['std_add'] = i['std_add']
#     x[id]['str_add'] = i['norm_add']
#     x[id]['NT_str_add'] = i['NT_norm_add']
#     # break

In [10]:
id = list(x.keys())

In [11]:
print(len(id))
print(id[-1])

34481
36660


In [8]:
# with open('Data/RAT_DATA_MAIN_New.json', 'w', encoding='utf-8') as f:
#     json.dump(x, f, ensure_ascii=False, indent=4)

In [35]:
data = []
for i in RAT_DATA:
    # print(RAT_DATA[i]['std_add'])
    std_add = RAT_DATA[i]['std_add']
    std_add['id'] = i
    if 'ward' not in std_add:
        std_add['ward'] = 'None'
    elif 'street' not in std_add:
        std_add['street'] = 'None'
    elif 'ward' not in std_add and 'street' not in std_add:
        std_add['ward'] = 'None'
        std_add['street'] = 'None'
    data.append(std_add)
    # break 

In [36]:
len(data)

34481

In [68]:
# data
import pandas as pd 
df = pd.DataFrame.from_dict(data, orient='columns')

In [69]:
new_df = df.drop(columns=['street', 'ward', 'id'])

In [70]:
new_df

district         city
0      bình chánh  hồ chí minh
1      bình chánh  hồ chí minh
2      bình chánh  hồ chí minh
3      bình chánh  hồ chí minh
4      bình chánh  hồ chí minh
...           ...          ...
34476    yên bình      yên bái
34477    yên bình      yên bái
34478    yên bình      yên bái
34479    yên bình      yên bái
34480    yên bình      yên bái

[34481 rows x 2 columns]

In [71]:
new_df = new_df.drop_duplicates()

In [72]:
new_df

district         city
0      bình chánh  hồ chí minh
298      bình tân  hồ chí minh
697    bình thạnh  hồ chí minh
861       cần giờ  hồ chí minh
923        củ chi  hồ chí minh
...           ...          ...
34264    trấn yên      yên bái
34280    văn chấn      yên bái
34312     văn yên      yên bái
34359     yên bái      yên bái
34456    yên bình      yên bái

[705 rows x 2 columns]

In [53]:
exist_addresses = set()
for i in RAT_DATA:
    # print(RAT_DATA[i]['std_add'])
    # break
    x = RAT_DATA[i]['std_add']
    if x['street'] == 'None' and x['ward'] == 'None':
        exist_addresses.add(x['district']+x['city'])

In [55]:
# len(exist_addresses)
exist_addresses = list(exist_addresses)

In [65]:
exist_addresses[:20]

['tiên dubắc ninh',
 'tam dươngvĩnh phúc',
 'bàu bàngbình dương',
 'tân uyênbình dương',
 'hải châuđà nẵng',
 'hà đônghà nội',
 'đan phượnghà nội',
 'bến cátbình dương',
 'tây hồhà nội',
 'quận 2hồ chí minh',
 'phú nhuậnhồ chí minh',
 'sông côngthái nguyên',
 'quận 7hồ chí minh',
 'rạch giákiên giang',
 'quy nhơnbình định',
 'hàm thuận nambình thuận',
 'gò vấphồ chí minh',
 'thủ đứchồ chí minh',
 'thủ thừalong an',
 'quận 9hồ chí minh']

In [74]:
str_addresses = []
for index, row in new_df.iterrows():
    # print(row['district'])
    # print(row['city'])
    str_addresses.append(row['district']+row['city'])
    # break
new_df['str_address'] = str_addresses

<ipython-input-74-bbc2befc6f01>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['str_address'] = str_addresses


In [75]:
new_df.head(20)

district         city            str_address
0     bình chánh  hồ chí minh  bình chánhhồ chí minh
298     bình tân  hồ chí minh    bình tânhồ chí minh
697   bình thạnh  hồ chí minh  bình thạnhhồ chí minh
861      cần giờ  hồ chí minh     cần giờhồ chí minh
923       củ chi  hồ chí minh      củ chihồ chí minh
1133      gò vấp  hồ chí minh      gò vấphồ chí minh
1349     hóc môn  hồ chí minh     hóc mônhồ chí minh
1745      nhà bè  hồ chí minh      nhà bèhồ chí minh
1797   phú nhuận  hồ chí minh   phú nhuậnhồ chí minh
1909      quận 1  hồ chí minh      quận 1hồ chí minh
2087     quận 10  hồ chí minh     quận 10hồ chí minh
2221     quận 11  hồ chí minh     quận 11hồ chí minh
2333     quận 12  hồ chí minh     quận 12hồ chí minh
2767      quận 2  hồ chí minh      quận 2hồ chí minh
3057      quận 3  hồ chí minh      quận 3hồ chí minh
3157      quận 4  hồ chí minh      quận 4hồ chí minh
3261      quận 5  hồ chí minh      quận 5hồ chí minh
3382      quận 6  hồ chí minh      quận 6hồ chí minh
3544      quận 7  hồ chí minh      quận 7hồ chí minh
3774      quận 8  hồ chí minh      quận 8hồ chí minh

In [76]:
criterion = lambda row: row['str_address'] not in exist_addresses

new_df = new_df[new_df.apply(criterion, axis=1)]

In [82]:
new_df

district         city         str_address
861      cần giờ  hồ chí minh  cần giờhồ chí minh
6969      mỹ đức       hà nội        mỹ đứchà nội
7440   thanh oai       hà nội     thanh oaihà nội
7649     ứng hòa       hà nội       ứng hòahà nội
10026   hòa vang      đà nẵng     hòa vangđà nẵng
...          ...          ...                 ...
34253   trạm tấu      yên bái     trạm tấuyên bái
34264   trấn yên      yên bái     trấn yênyên bái
34280   văn chấn      yên bái     văn chấnyên bái
34312    văn yên      yên bái      văn yênyên bái
34456   yên bình      yên bái     yên bìnhyên bái

[538 rows x 3 columns]

In [78]:
import json
with open ('Data/RAT_DATA_MAIN_New.json', 'r', encoding='utf-8') as f:
    RAT_DATA = json.load(f)

In [80]:
current_id = int(list(RAT_DATA.keys())[-1])+1
print(current_id)

36661


In [83]:
from Preprocess import remove_tone_of_text
remove_tone_of_text('Cao Hải Nảm')

'Cao Hai Nam'

In [84]:
str_addresses = []
for index, row in new_df.iterrows():
    RAT_DATA[current_id] = dict()
    district, city = row['district'], row['city']
    # print(district)
    # print(city)
    RAT_DATA[current_id]['std_add'] = dict()
    RAT_DATA[current_id]['std_add']['district'] = district
    RAT_DATA[current_id]['std_add']['city'] = city
    RAT_DATA[current_id]['str_add'] = ' '.join([district, city])
    RAT_DATA[current_id]['NT_str_add'] = ' '.join([remove_tone_of_text(district), remove_tone_of_text(city)])
    current_id += 1
    # break

In [55]:
len(RAT_DATA)

35019

In [87]:
with open('Data/RAT_DATA_MAIN_New_Update.json', 'w', encoding='utf-8') as f:
    json.dump(RAT_DATA, f, ensure_ascii=False, indent=4)

In [2]:
import json
with open ('Data/RAT_DATA_MAIN_New_Update.json', 'r', encoding='utf-8') as f:
    RAT_DATA = json.load(f)

In [3]:
count = 0
for i in RAT_DATA:
    print(RAT_DATA[i])
    break

{'std_add': {'street': 'đường 1', 'district': 'bình chánh', 'city': 'hồ chí minh'}, 'str_add': 'đường 1 bình chánh hồ chí minh', 'NT_str_add': 'duong 1 binh chanh ho chi minh'}


In [6]:
count = 0
for i in RAT_DATA:
    if 'ward' in RAT_DATA[i]['std_add']:
        count += 1

In [9]:
import pandas as pd

In [24]:
df = pd.read_csv('Data/ward_level.csv')
df['Cấp'].drop_duplicates()

0         Phường
126     Thị trấn
127           Xã
3797       Huyện
Name: Cấp, dtype: object

In [40]:
df = pd.read_csv('Data/ward_level.csv')
print(len(df))
# df = df[df['Cấp'].isnull()]
df = df.dropna()

10604


In [41]:
df['Cấp'].drop_duplicates()

0        Phường
126    Thị trấn
127          Xã
Name: Cấp, dtype: object

In [42]:
len(df)

10599

In [45]:
df.to_csv('Data/ward_level.csv', index=False)

# Re produce sentence transformers from transformers

In [1]:
from transformers import AutoModel, AutoTokenizer
import torch
model = AutoModel.from_pretrained('sentence-transformer_LaBSE')
tokenizer = AutoTokenizer.from_pretrained('sentence-transformer_LaBSE')

In [3]:
sent = 'vĩnh hùng vĩnh lộc thanh hóa'

In [5]:
inputs = tokenizer(sent, return_tensors='pt')
with torch.no_grad():
    outputs = model(**inputs)

In [7]:
vector = outputs['pooler_output']
vector = torch.nn.functional.normalize(vector, p=2, dim=1).detach().numpy()

# Build new address matrix

In [7]:
import json
with open('Data/RAT_DATA_MAIN.json', 'r', encoding='utf-8') as f:
    RAT_DATA = json.load(f)

In [8]:
len(RAT_DATA)

35019

In [9]:
import Parameters
import numpy as np
import Utils
from transformers import AutoModel, AutoTokenizer

In [113]:
# norm_embeddings.shape

(34481, 772)

In [10]:
model = AutoModel.from_pretrained(Parameters.local_embedding_model)
tokenizer = AutoTokenizer.from_pretrained(Parameters.local_embedding_model)

In [11]:
for i in RAT_DATA:
    print(RAT_DATA[i])
    break

{'std_add': {'street': 'đường 1', 'district': 'bình chánh', 'city': 'hồ chí minh'}, 'str_add': 'đường 1 bình chánh hồ chí minh', 'NT_str_add': 'duong 1 binh chanh ho chi minh'}


In [12]:
str_adds, NT_str_adds = [], []
for i in RAT_DATA:
    str_adds.append(RAT_DATA[i]['str_add'])
    NT_str_adds.append(RAT_DATA[i]['NT_str_add'])

In [13]:
print(len(str_adds))
print(len(NT_str_adds))

35019
35019


In [9]:
# str_add_matrix, NT_str_add_matrix = [], []
# for i in range(0, len(str_adds[:200])):
#     str_add, NT_str_add = str_adds[i], NT_str_adds[i]
#     str_add_matrix.append(Utils.encode(model, tokenizer, str_add))
#     NT_str_add_matrix.append(Utils.encode(model, tokenizer, NT_str_add))
#     # break

In [14]:
str_add_matrix, NT_str_add_matrix = [], []
batchsize = 256
n = len(str_adds)
for i in range(0, len(str_adds[:n]), batchsize):
    str_add, NT_str_add = str_adds[:n][i:i+batchsize], NT_str_adds[:n][i:i+batchsize]
    str_add_matrix.extend(Utils.encode(model, tokenizer, str_add))
    NT_str_add_matrix.extend(Utils.encode(model, tokenizer, NT_str_add))

In [24]:
# str_add_matrix

In [15]:
str_add_matrix = np.array(str_add_matrix)
NT_str_add_matrix = np.array(NT_str_add_matrix)

In [16]:
NT_str_add_matrix.shape

(35019, 768)

In [17]:
entity_matrix = []
str_adds, NT_str_adds = [], []
for i in RAT_DATA:
    std_add = RAT_DATA[i]['std_add']
    print(std_add)
    break

{'street': 'đường 1', 'district': 'bình chánh', 'city': 'hồ chí minh'}


In [18]:
entity_matrix = []
entities = ['street', 'ward', 'district', 'city']
str_adds, NT_str_adds = [], []
for i in RAT_DATA:
    std_add = RAT_DATA[i]['std_add']
    entity_vector = [0., 0., 0., 0.]
    for ent in entities:
        if ent in std_add:
            entity_vector[entities.index(ent)] = 1. 
    # print(entity_vector)
    entity_matrix.append(entity_vector)
    # break

In [19]:
entity_matrix = np.array(entity_matrix)

In [20]:
entity_matrix.shape

(35019, 4)

In [21]:
x = np.concatenate((str_add_matrix, entity_matrix), axis=1)
NT_x = np.concatenate((NT_str_add_matrix, entity_matrix), axis=1)

In [22]:
x.shape

(35019, 772)

In [23]:
NT_x.shape

(35019, 772)

In [24]:
with open('Data/std_address_matrix.npy', 'wb') as f:
    np.save(f, x)
    np.save(f, NT_x)
# with open('Data/Update_NT_norm.npy', 'wb') as f:
#     np.save(f, NT_x)

# Build RAT only contain WARD level

In [12]:
import Parameters
import numpy as np
import Utils

In [3]:
import json
with open('Data/RAT_DATA_MAIN.json', 'r', encoding='utf-8') as f:
    RAT_DATA = json.load(f)
with open(file=Parameters.ID2id_FILE, mode='r', encoding='utf-8') as f:
    ID2id = json.load(fp=f)
with open(file=Parameters.id2ID_FILE, mode='r', encoding='utf-8') as f:
    id2ID = json.load(fp=f)

In [4]:
for i in RAT_DATA:
    print(RAT_DATA[i])
    break

{'std_add': {'street': 'đường 1', 'district': 'bình chánh', 'city': 'hồ chí minh'}, 'str_add': 'đường 1 bình chánh hồ chí minh', 'NT_str_add': 'duong 1 binh chanh ho chi minh'}


In [5]:
with open(Parameters.STD_EMBEDDING_FILE, 'rb') as f:
    std_embeddings = np.load(f)
    NT_std_embeddings = np.load(f)

In [13]:
ward_id2ID, ward_ID2id = dict(), dict()
RAT_DATA_Ward = dict()
ward_str_add_matrix, ward_NT_str_add_matrix = [], []
count = 0
for id in RAT_DATA:
    std_add = RAT_DATA[id]['std_add']
    if 'street' not in std_add:
        RAT_DATA_Ward[id] = RAT_DATA[id]
        ward_ID2id[count] = id 
        ward_id2ID[id] = count
        count += 1

        ID = int(id2ID[id])
        ward_str_add_matrix.append(std_embeddings[ID])
        ward_NT_str_add_matrix.append(NT_std_embeddings[ID])

In [14]:
print(len(ward_ID2id))
print(len(ward_id2ID))
print(len(ward_str_add_matrix))
print(len(ward_NT_str_add_matrix))

11860
11860
11860
11860


In [15]:
ward_str_add_matrix = np.array(ward_str_add_matrix)
ward_NT_str_add_matrix = np.array(ward_NT_str_add_matrix)

In [16]:
with open('Data/ward_id2ID.json', 'w', encoding='utf-8') as f:
    json.dump(ward_id2ID, f, ensure_ascii=False, indent=4)
with open('Data/ward_ID2id.json', 'w', encoding='utf-8') as f:
    json.dump(ward_ID2id, f, ensure_ascii=False, indent=4)
with open('Data/ward_std_address_matrix.npy', 'wb') as f:
    np.save(f, ward_str_add_matrix)
    np.save(f, ward_NT_str_add_matrix)

In [15]:
print(len(RAT_DATA_Ward))

11155


# Update id2ID, ID2id, id2norm_add

In [49]:
import json
import Parameters
with open('Data/RAT_DATA_MAIN_New_Update.json', 'r', encoding='utf-8') as f:
    RAT_DATA = json.load(f)

In [47]:
for i in RAT_DATA:
    print(RAT_DATA[i])
    break

{'std_add': {'street': 'đường 1', 'district': 'bình chánh', 'city': 'hồ chí minh'}, 'str_add': 'đường 1 bình chánh hồ chí minh', 'NT_str_add': 'duong 1 binh chanh ho chi minh'}


In [ ]:
import json
with open('Data/RAT_DATA_MAIN_New_Update.json', 'r', encoding='utf-8') as f:
    RAT_DATA = json.load(f)

In [50]:
with open(file=Parameters.ID2id_FILE, mode='r', encoding='utf-8') as f:
    ID2id = json.load(fp=f)

with open(file=Parameters.id2ID_FILE, mode='r', encoding='utf-8') as f:
    id2ID = json.load(fp=f)

with open(file=Parameters.id2norm_add_FILE, mode='r', encoding='utf-8') as f:
    id2std_add= json.load(fp=f)

In [56]:
id2std_add['0']

{'norm_add': 'đường 1 bình chánh hồ chí minh',
 'NT_norm_add': 'duong 1 binh chanh ho chi minh'}

In [57]:
ID2id, id2ID, id2std_add = dict(), dict(), dict()
count = 0
for i in RAT_DATA:
    ID2id[count] = int(i)
    id2ID[i] = count
    id2std_add[i] = dict()
    id2std_add[i]['str_add'] = RAT_DATA[i]['str_add']
    id2std_add[i]['NT_str_add'] = RAT_DATA[i]['NT_str_add']
    count += 1

In [60]:
with open('Data/id2ID_Update.json', 'w', encoding='utf-8') as f:
    json.dump(id2ID, f, ensure_ascii=False, indent=4)
with open('Data/ID2id_Update.json', 'w', encoding='utf-8') as f:
    json.dump(ID2id, f, ensure_ascii=False, indent=4)
with open('Data/id2norm_add_Update.json', 'w', encoding='utf-8') as f:
    json.dump(id2std_add, f, ensure_ascii=False, indent=4)

In [61]:
with open(file=Parameters.id2norm_add_FILE, mode='r', encoding='utf-8') as f:
    id2std_add= json.load(fp=f)

In [63]:
x = dict()
for i in id2std_add:
    x[i] = dict()
    x[i]['std_add'] = id2std_add[i]['norm_add']
    x[i]['NT_std_add'] = id2std_add[i]['NT_norm_add']

In [64]:
with open('Data/id2norm_add_1.json', 'w', encoding='utf-8') as f:
    json.dump(x, f, ensure_ascii=False, indent=4)

In [ ]:
import json
import Parameters
with open('Data/RAT_DATA_MAIN.json', 'r', encoding='utf-8') as f:
    RAT_DATA = json.load(f)

# Test Siameser

In [1]:
import keras
import Siameser

2022-06-17 10:17:12.012932: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-17 10:17:12.012947: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/namch/anaconda3/envs/vas/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
std = Siameser.Siameser('AD')

Load model


2022-06-17 10:17:13.937805: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-06-17 10:17:13.937824: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-06-17 10:17:13.937838: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (namch): /proc/driver/nvidia/version does not exist
2022-06-17 10:17:13.938006: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Load sentence embedding model (If this is the first time you run this repo, It could be take time to download sentence embedding model)
Load standard address
Load standard address matrix
Done


In [4]:
# add = 'Hoi P Bình Hưng Hòa B/Tân TP Hồ Chí Minh'
# add = 'Thị Tĩnh Khai P Đa Kao Quận 1 TP Hồ Chí Minh'
# add = 'Huy tinn T Phát Thị Trấn Nhà Bè NB TP Hồ Chí Minh'
# add = 'Văn Nguyên P T-Định Q1 TP Hồ Chí-Minh'
# add = 'Lão Bang Quận Hải Châu Đà Nẵng'
# add = 'P Than P BTĐông BTân TP Hồ Chí Minh'
# add = 'Xuân phương Từ liêm Hà nội'
# add = 'Mỹ Tây Tây Hoà Phú Yên'
# add = 'Lãm P An Lạc Bình Tân TP Hồ Chí Minh'
# add = 'Tân Thanh Bà Rịa-Vũng Tàu'
# add = 'TT Bộ Thủy Sân Ngọc Khánh Ba Đình Hà Nội'
# add = 'kê thủy quảng bình'
add = 'P.Hồng Sơn Thành phố Vinh, Nghệ An'
# add = '150 kim hoa hà nội'
# add = 'kim hoa hà nội'
# add = 'đường 18 , phường giếng đáy , hạ long , quảng ninh'
std_add = std.get_top_k(add, 10)
print(std_add)

1095/1095 [==============================] - 1s 1ms/step
[{'street': 'bùi mộng hoa', 'district': 'kiến an', 'city': 'hải phòng'}, {'street': 'hồng sơn', 'district': 'vinh', 'city': 'nghệ an'}, {'ward': 'hồng sơn', 'district': 'vinh', 'city': 'nghệ an'}, {'district': 'kỳ sơn', 'city': 'hòa bình'}, {'street': 'bình minh', 'district': 'đồ sơn', 'city': 'hải phòng'}, {'street': 'hương sơn', 'district': 'kiến an', 'city': 'hải phòng'}, {'street': 'hoa khê', 'district': 'kiến an', 'city': 'hải phòng'}, {'ward': 'hương sơn', 'district': 'bình xuyên', 'city': 'vĩnh phúc'}, {'street': 'đống công tường', 'district': 'cẩm lệ', 'city': 'đà nẵng'}, {'ward': 'vân mộng', 'district': 'lộc bình', 'city': 'lạng sơn'}]


# Rebuild file

In [1]:
import json

In [2]:
id2ID, ID2id, id2std_add = dict(), dict(), dict()
with open('Data/RAT_DATA_MAIN_New_Update.json', 'r') as f:
    RAT_DATA = json.load(f)

In [3]:
len(RAT_DATA)

35019

In [4]:
for i in RAT_DATA:
    print(i)
    print(RAT_DATA[i])
    break

0
{'std_add': {'street': 'đường 1', 'district': 'bình chánh', 'city': 'hồ chí minh'}, 'str_add': 'đường 1 bình chánh hồ chí minh', 'NT_str_add': 'duong 1 binh chanh ho chi minh'}


In [6]:
cur_ID = 0
for i in RAT_DATA:
    id2ID[i] = cur_ID
    ID2id[cur_ID] = i 
    cur_ID += 1

In [8]:
with open('Data/id2ID_Update.json', 'w', encoding='utf-8') as f:
    json.dump(id2ID, f, ensure_ascii=False, indent=4)
with open('Data/ID2id_Update.json', 'w', encoding='utf-8') as f:
    json.dump(ID2id, f, ensure_ascii=False, indent=4)

In [4]:
id2str_std_add = dict()
for i in RAT_DATA:
    id2str_std_add[i] = dict()
    id2str_std_add[i]['str_add'] = RAT_DATA[i]['str_add']
    id2str_std_add[i]['NT_str_add'] = RAT_DATA[i]['NT_str_add']

In [5]:
with open('Data/id2str_std_add.json', 'w', encoding='utf-8') as f:
    json.dump(id2str_std_add, f, ensure_ascii=False, indent=4)

# Test model on VPS data

In [11]:
import keras 
import Siameser
import gc
import normalize_vietnamese_typing
import Utils

In [7]:
std = Siameser.Siameser('AD', 'ward')

Load model
Load sentence embedding model (If this is the first time you run this repo, It could be take time to download sentence embedding model)
Load standard address
Load standard address matrix
Done


In [27]:
# add = 'Hoàng Hoa Thám Thụy Khuê Tây Hồ, Hà Nội'
# add = 'TT.Nông Cống, Nông Cống, Thanh Hoá'
# add = 'Hòa Châu, huyện Hoà Vang, thịphố Đà Nẵng'
# add = '39 Trần Hưng- Đạo, P.Ng-T-Bình, Q1, TP. Hồ Chí Minh'
# add  = 'Hà Huy Tập, TP. Vinh, Nghệ An '
# print(add)
# add = Utils.remove_tone_of_text(add)
# std.get_top_k(add, 10)
add = 'P. Hồng Sơn Thành phố Vinh, Nghệ An '
std.standardize(add)

371/371 [==============================] - 1s 1ms/step


{'ward': 'hồng sơn', 'district': 'vinh', 'city': 'nghệ an'}

In [18]:
print(len('080106_CARD1_all.dumps,'))

23


In [23]:
with open('Data/VPS/fdm.txt') as f:
    addresses = []
    for line in f:
        line = line[23:].strip('\n')
        addresses.append(line)
with open('Data/VPS/truncate_fdm.txt') as f:
    groundtruth_addresses = []
    for line in f:
        line = line[23:].strip('\n')
        groundtruth_addresses.append(line)

In [5]:
# addresses[:10]

In [4]:
# groundtruth_addresses[:10]

In [25]:
for idx, add in enumerate(addresses[:20]):
    print(add)
    std_add = std.standardize(add)
    std_add = ', '.join([std_add[i] for i in std_add])
    print(std_add)
    print(groundtruth_addresses[idx])
    print('\n')
    gc.collect()

134 Chùa Bộc Tổ 34 Quang Trung, Đống Đa, Hà Nội 
371/371 [==============================] - 1s 1ms/step
mường khương, mường khương, lào cai
Phường Quang Trung, Quận Đống Đa, Thành Phố Hà Nội


P. Ấp 3, Xuân Tân Xuân Lộc, Đồng Nai 
371/371 [==============================] - 0s 1ms/step
xuân tân, long khánh, đồng nai
Phường Xuân Tân, Huyện Xuân Lộc, Tỉnh Đồng Nai


Phường 5, TP Cà Mau, Cà Mau 
371/371 [==============================] - 1s 1ms/step
phường 5, cà mau, cà mau
Phường 5, Thành Phố Cà Mau, Tỉnh Cà Mau


Thị trấn Quỳ Hợp Huyện Quỳ Hợp, Nghệ An 
371/371 [==============================] - 1s 1ms/step
quỳ hợp, nghệ an
Thị Trấn Quỳ Hợp, Huyện Quỳ Hợp, Tỉnh Nghệ An


25 Ngõ Hàng Thịt Cửa Nam, Hoàn Kiếm, Hà Nội 
371/371 [==============================] - 0s 1ms/step
định công, hoàng mai, hà nội
Phường Cửa Nam, Quận Hoàn Kiếm, Thành Phố Hà Nội


TDP Số 2, Cổ Nhuế 2 Bắc Từ Liêm, Hà Nội 
371/371 [==============================] - 1s 1ms/step
đất cuốc, tân uyên, bình dương
Phường Cổ Nhuế 

In [11]:
for idx, add in enumerate(addresses[:100]):
    print(add)
    std_adds = std.get_top_k(add, 5)
    for std_add in std_adds:
        std_add = ', '.join([std_add[i] for i in std_add])
        print(std_add)
    print(groundtruth_addresses[idx])
    print('\n')
    gc.collect()

134 Chùa Bộc Tổ 34 Quang Trung, Đống Đa, Hà Nội 
371/371 [==============================] - 0s 1ms/step
mường khương, mường khương, lào cai
mường khương, lào cai
thanh đa, phúc thọ, hà nội
vạn ninh, khánh hòa
diên lạc, diên khánh, khánh hòa
Phường Quang Trung, Quận Đống Đa, Thành Phố Hà Nội


P. Ấp 3, Xuân Tân Xuân Lộc, Đồng Nai 
371/371 [==============================] - 0s 1ms/step
xuân tân, long khánh, đồng nai
xuân trường, xuân lộc, đồng nai
bửu long, biên hòa, đồng nai
xuân thọ, xuân lộc, đồng nai
tân hưng, bàu bàng, bình dương
Phường Xuân Tân, Huyện Xuân Lộc, Tỉnh Đồng Nai


Phường 5, TP Cà Mau, Cà Mau 
371/371 [==============================] - 0s 1ms/step
phường 5, cà mau, cà mau
tam đường, tam đường, lai châu
ðại phước, càng long, trà vinh
nà tăm, tam đường, lai châu
mù sang, phong thổ, lai châu
Phường 5, Thành Phố Cà Mau, Tỉnh Cà Mau


Thị trấn Quỳ Hợp Huyện Quỳ Hợp, Nghệ An 
371/371 [==============================] - 0s 1ms/step
quỳ hợp, nghệ an
yên hợp, quỳ hợp, nghệ an
quỳ

# Gen data to train model

In [45]:
import Utils
import json
from transformers import AutoTokenizer, AutoModel
import Parameters
import random
import torch
from torch.utils.data import DataLoader, TensorDataset, SequentialSampler
import numpy as np

In [6]:
with open(Parameters.TRAIN_DATA_FILE, 'r', encoding='utf-8') as f:
    train_data = json.load(f)
with open(Parameters.NORM_ADDS_FILE, 'r', encoding='utf-8') as f:
    RAT_DATA = json.load(f)

num_negative = 15

In [7]:
print(len(train_data['data']))
print(len(RAT_DATA))

1000
35019


In [4]:
for i in range(len(train_data['data'])):
    print(train_data['data'][i])
    break

{'id': 0, 'noisy_add': 'đông lân 1 , phường bà điểm , hồ chí minh', 'std_add': {'1580': {'street': 'đông lân 1', 'city': 'hồ chí minh', 'id': 1580, 'district': 'hóc môn', 'ward': 'None'}}}


In [5]:
# Preprocess.remove_punctuation('đông lân 1 , phường bà điểm , hồ chí minh')
Utils.remove_tone_of_text('đông lân 1 , phường bà điểm , hồ chí minh')

'dong lan 1 , phuong ba diem , ho chi minh'

In [15]:
# tokenizer = AutoTokenizer.from_pretrained(Parameters.local_embedding_model)
# print(tokenizer('đông lân 1 phường bà điểm hồ chí minh'))
# print(tokenizer(Preprocess.remove_punctuation('đông lân 1 , phường bà điểm , hồ chí minh')))

In [16]:
# tokenizer.convert_ids_to_tokens(tokenizer('đông lân 1 , phường bà điểm , hồ chí minh')['input_ids'])
# tokenizer.convert_ids_to_tokens(tokenizer(Preprocess.remove_punctuation('đông lân 1 , phường bà điểm , hồ chí minh'))['input_ids'])

In [27]:
id = [i for i in id2str_std_add]
print(len(id))
id.remove('0')
print(len(id))

35019
35018


In [84]:
data = []
for i in range(len(train_data['data'])):
    batch = []
    sample = train_data['data'][i]
    add = sample['noisy_add']
    id = list(sample['std_add'].keys())[0]
    # print(id2str_std_add[id])
    id_list = [i for i in RAT_DATA]
    random.shuffle(id_list)
    id_list.remove(id)
    negative_id = id_list[:num_negative]
    if add == Utils.remove_tone_of_text(add):
        str_std_add = RAT_DATA[id]['NT_str_add']
        ent_vector = Utils.gen_entity_vector_from_std_add(RAT_DATA[id]['std_add'])
        batch.append([add, str_std_add, ent_vector, 1.])
        for neg_id in negative_id:
            neg_std_add = RAT_DATA[neg_id]['NT_str_add']
            ent_vector = Utils.gen_entity_vector_from_std_add(RAT_DATA[neg_id]['NT_std_add'])
            batch.append([add, neg_std_add, ent_vector, -1.])
    else:
        str_std_add = RAT_DATA[id]['str_add']
        ent_vector = Utils.gen_entity_vector_from_std_add(RAT_DATA[id]['std_add'])
        batch.append([add, str_std_add, ent_vector, 1.])
        for neg_id in negative_id:
            neg_std_add = RAT_DATA[neg_id]['str_add']
            ent_vector = Utils.gen_entity_vector_from_std_add(RAT_DATA[neg_id]['std_add'])
            batch.append([add, neg_std_add, ent_vector, -1.])
    data.append(batch)
    break

In [85]:
data

[[['đông lân 1 , phường bà điểm , hồ chí minh',
   'đông lân 1 hóc môn hồ chí minh',
   array([[1., 0., 1., 1.]]),
   1.0],
  ['đông lân 1 , phường bà điểm , hồ chí minh',
   'phú thịnh đại từ thái nguyên',
   array([[0., 1., 1., 1.]]),
   -1.0],
  ['đông lân 1 , phường bà điểm , hồ chí minh',
   'phan bội châu tam kỳ quảng nam',
   array([[1., 0., 1., 1.]]),
   -1.0],
  ['đông lân 1 , phường bà điểm , hồ chí minh',
   'vĩnh lộc bình chánh hồ chí minh',
   array([[1., 0., 1., 1.]]),
   -1.0],
  ['đông lân 1 , phường bà điểm , hồ chí minh',
   'quốc lộ 91 châu đốc an giang',
   array([[1., 0., 1., 1.]]),
   -1.0],
  ['đông lân 1 , phường bà điểm , hồ chí minh',
   'canh nông 2 hải dương hải dương',
   array([[1., 0., 1., 1.]]),
   -1.0],
  ['đông lân 1 , phường bà điểm , hồ chí minh',
   'trương tấn sang đức hòa long an',
   array([[1., 0., 1., 1.]]),
   -1.0],
  ['đông lân 1 , phường bà điểm , hồ chí minh',
   'yên hợp văn yên yên bái',
   array([[0., 1., 1., 1.]]),
   -1.0],
  ['đông 

In [65]:
tokenizer = AutoTokenizer.from_pretrained(Parameters.local_embedding_model)
embedding_model = AutoModel.from_pretrained(Parameters.local_embedding_model)

In [66]:
class AddressStandardization(torch.nn.Module):
    def __init__(self, embedding_model):
        super(AddressStandardization, self).__init__()
        self.embedding_model = embedding_model

    def forward(self, raw_ids, raw_mask, raw_ent_vectors, std_ids, std_mask, std_ent_vectors):
        raw_vector = torch.cat((self.embedding_model(raw_ids, raw_mask)['last_hidden_state'][:, 0, :], raw_ent_vectors), axis=1)
        std_vector = torch.cat((self.embedding_model(std_ids, std_mask)['last_hidden_state'][:, 0, :], std_ent_vectors), axis=1)
        return torch.nn.CosineSimilarity(dim=1, eps=1e-6)(raw_vector, std_vector)

In [50]:
model = AddressStandardization(embedding_model)

In [67]:
x = data[0][0]
x

['đông lân 1 , phường bà điểm , hồ chí minh',
 'lý ông trọng đà lạt lâm đồng',
 array([[1., 0., 1., 1.]]),
 -1.0]

In [68]:
len(data[0])

16

In [81]:
def GenericDataLoader(data, batch_size):
    # raw_add, raw_entity, std_add, std_entity = GenericData()
    raw_ids, raw_masks, raw_ent_vectors, std_ids, std_masks, std_ent_vectors, labels = [], [], [], [], [], [], []    
    for batch in data:
        raw_add = batch[0][0]
        raw_ent_vector = Utils.gen_entity_vector_from_raw_add(raw_add)
        for sample in batch:
            raw_add, std_add, std_ent_vector, label = sample
            raw_input = tokenizer(raw_add, return_tensors="np", padding='max_length', truncation=True, max_length=32)
            raw_ids.append(raw_input['input_ids'][0])
            raw_masks.append(raw_input['attention_mask'][0])
            
            std_input = tokenizer(std_add, return_tensors="np", padding='max_length', truncation=True, max_length=32)
            std_ids.append(std_input['input_ids'][0])
            std_masks.append(std_input['attention_mask'][0])

            raw_ent_vectors.append(raw_ent_vector)
            std_ent_vectors.append(std_ent_vector)

            labels.append(label)

    raw_ids = torch.tensor(np.array(raw_ids))
    raw_masks = torch.tensor(np.array(raw_masks))
    raw_ent_vectors = torch.tensor(np.array(raw_ent_vectors))

    std_ids = torch.tensor(np.array(std_ids))
    std_masks = torch.tensor(np.array(std_masks))
    std_ent_vectors = torch.tensor(np.array(std_ent_vectors))

    labels = torch.tensor(np.array(labels))

    data = TensorDataset(raw_ids, raw_masks, raw_ent_vectors, std_ids, std_masks, std_ent_vectors, labels)
    sampler = SequentialSampler(data)
    dataloader = DataLoader(data, sampler=sampler, batch_size=batch_size)
    return dataloader

In [86]:
train_dataloader = GenericDataLoader(data, 4)

In [90]:
for step, batch in enumerate(train_dataloader):
    b_raw_ids = batch[0]
    b_raw_mask = batch[1]
    b_raw_entity = batch[2].reshape(-1, 4)
    b_std_ids = batch[3]
    b_std_mask = batch[4]
    b_std_entity = batch[5].reshape(-1, 4)
    b_labels = batch[6]

    print(b_raw_ids.shape)
    print(b_raw_entity.shape)
    print(b_labels.shape)
    model.zero_grad()
    outputs = model(b_raw_ids,
                    b_raw_mask,
                    b_raw_entity,
                    b_std_ids,
                    b_std_mask,
                    b_std_entity 
                    )
    print(outputs.shape)
    print(b_labels)
    print(outputs)
    loss = torch.nn.MSELoss()(outputs, b_labels)
    print(loss)
    # break

torch.Size([4, 32])
torch.Size([4, 4])
torch.Size([4])
torch.Size([4])
tensor([ 1., -1., -1., -1.], dtype=torch.float64)
tensor([0.8928, 0.6273, 0.7392, 0.7991], dtype=torch.float64,
       grad_fn=<DivBackward0>)
tensor(2.2303, dtype=torch.float64, grad_fn=<MseLossBackward0>)
torch.Size([4, 32])
torch.Size([4, 4])
torch.Size([4])
torch.Size([4])
tensor([-1., -1., -1., -1.], dtype=torch.float64)
tensor([0.6604, 0.6613, 0.6560, 0.6165], dtype=torch.float64,
       grad_fn=<DivBackward0>)
tensor(2.7180, dtype=torch.float64, grad_fn=<MseLossBackward0>)
torch.Size([4, 32])
torch.Size([4, 4])
torch.Size([4])
torch.Size([4])
tensor([-1., -1., -1., -1.], dtype=torch.float64)
tensor([0.7181, 0.7047, 0.7124, 0.6488], dtype=torch.float64,
       grad_fn=<DivBackward0>)
tensor(2.8772, dtype=torch.float64, grad_fn=<MseLossBackward0>)
torch.Size([4, 32])
torch.Size([4, 4])
torch.Size([4])
torch.Size([4])
tensor([-1., -1., -1., -1.], dtype=torch.float64)
tensor([0.6610, 0.7193, 0.7161, 0.5961], dtyp

In [74]:
outputs

tensor([0.6575, 0.7009, 0.6831, 0.7807], dtype=torch.float64,
       grad_fn=<DivBackward0>)